name: active_ecommerce_flutter
description: This is the flutter mobile application for active ecommerce cms

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.

# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.1.0+30

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.0
  json_annotation: ^4.1.0
  logging: ^1.0.2
  connectivity: ^3.0.6
  shimmer: ^3.0.0
  bordered_text: ^2.0.0
  flutter_html: ^3.0.0-beta.1
  flutter_svg: ^2.0.6
  url_launcher: ^6.0.12
  toast: ^0.3.0
  shared_preferences: ^2.0.8
  dotted_line: ^3.0.1
  timeline_list: ^0.0.3
  webview_flutter: ^4.2.0
  clipboard: ^0.1.2+8
  google_fonts: ^4.0.4
  flutter_rating_bar: ^4.0.0
  expandable: ^5.0.1
  dropdown_search: ^5.0.2
  flutter_countdown_timer: ^4.1.0
  package_info: ^2.0.2
  intl_phone_number_input: ^0.7.0+2
  flutter_chat_bubble: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  carousel_slider: ^4.0.0
  cached_network_image: ^3.1.0
  timeline_tile: ^2.0.0
  shared_value: ^3.0.0
  rename: ^2.0.1
  permission_handler: ^10.2.0
  image_picker: ^0.8.4+2
  flutter_facebook_auth: ^5.0.11
  google_sign_in: ^6.1.0
  google_maps_place_picker_mb: ^3.0.2
  firebase_messaging: ^14.6.0
  one_context: ^2.0.0
  social_share: ^2.2.1
  flutter_typeahead: ^4.0.0
  photo_view: ^0.14.0
  intl: ^0.18.0
  twitter_login: ^4.0.1
  sign_in_with_apple: ^4.0.0
  crypto: ^3.0.1
  validators: ^3.0.0
  flutter_math_fork: ^0.7.1
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.1
  flip_card: ^0.7.0
  badges: ^3.1.1
  route_transitions: ^2.0.1
  firebase_core: ^2.12.0
  flutter_local_notifications: ^14.0.0+2
  flutter_downloader: ^1.8.3+2
  path_provider: ^2.0.11
  google_maps_flutter: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  json_serializable: ^6.2.0
  flutter_launcher_icons: ^0.13.1




flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/htmls/
    - assets/fonts/
    - dummy_assets/
  fonts:
    - family: PublicSansSerif
      fonts:
        - asset: assets/fonts/PublicSans-Regular.ttf
        - asset: assets/fonts/PublicSans-Bold.ttf
        - asset: assets/fonts/PublicSans-Medium.ttf
        - asset: assets/fonts/PublicSans-SemiBold.ttf
        - asset: assets/fonts/PublicSans-Italic.ttf
          style: italic
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Medium.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #



  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
